version: '3'
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    networks:
      - redis_net
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf  # 启动哨兵，并且指定配置文件
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    networks:
      - redis_net
    ports:
      - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    networks:
      - redis_net
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
networks:  # 这里指定网络跟redis在同一个网络环境下
  redis_net:
    external:
      name: redis_net

